version: 1.0.{build}
before_build:
- cmd: nuget restore
build:
  project: Maybe.sln
  verbosity: minimal
after_build:
- cmd: nuget pack Maybe\Maybe.nuspec
artifacts:
- path: '**\Maybe*.nupkg'
  name: nuget
deploy:
  provider: NuGet
  api_key:
    secure: hV+W79F9Qx9wIeq7Kn/iYbnFbmDDR27CpDNR98VTOMOSGgnmdte2E5lFbGFEdJ7x
  skip_symbols: true
  artifact: /.Maybe*\.nupkg/