version: 1.0.{build}
configuration: Release
dotnet_csproj:
  patch: true
  file: Maybe\Maybe.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  account_feed: true
build_script:
- ps: .\build.ps1
artifacts:
- path: '**\Maybe*.nupkg'
  name: nuget-push