version: 1.0.{build}
before_build:
- cmd: nuget restore
build:
  project: Maybe.sln
  verbosity: minimal
after_build:
- cmd: nuget pack Maybe\Maybe.nuspec
artifacts:
- path: '**\Maybe*.nupkg'
  name: nuget