version: 1.0.{build}
before_build:
- cmd: nuget restore
build:
  project: Maybe.sln
  verbosity: minimal
  configuration:release
after_build:
- cmd: nuget pack Maybe\Maybe.nuspec -Version %appveyor_build_version%
artifacts:
- path: '**\Maybe*.nupkg'
  name: nuget
deploy:
  provider: NuGet
  name: NuGet
  on:
    branch: master
  api_key:
    secure: hV+W79F9Qx9wIeq7Kn/iYbnFbmDDR27CpDNR98VTOMOSGgnmdte2E5lFbGFEdJ7x
  skip_symbols: true
  artifact: /.*\.nupkg/
  