version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore
build:
  project: Maybe.sln
  verbosity: minimal
artifacts:
- path: '**\Maybe*.nupkg'
  name: nuget
deploy:
  provider: NuGet
  name: NuGet
  on:
    branch: master
  api_key:
    secure: hV+W79F9Qx9wIeq7Kn/iYbnFbmDDR27CpDNR98VTOMOSGgnmdte2E5lFbGFEdJ7x
  skip_symbols: true
  artifact: /.*\.nupkg/
  